
spring:
  session:
    store-type: none
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root

# 2.0 默认日期返回不是时间戳
  jackson:
    serialization:
      write-dates-as-timestamps: true

# 解决 NumberFormatException
logging:
  level.io.swagger.models.parameters.AbstractSerializableParameter: error


lbw:
  security:
    browser:
      loginType: JSON
    code:
      image:
        length: 6
        width: 100
        url: /user/*
#      loginPage: /demo-signIn.html
